# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cupos.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cupos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63upos.proto\x12\x04\x63upo\"\"\n\x0eObtenerRequest\x12\x10\n\x08\x63urso_id\x18\x01 \x01(\x05\"\'\n\x0fObtenerResponse\x12\x14\n\x0c\x63upos_libres\x18\x01 \x01(\x05\"\x0f\n\rListarRequest\"V\n\x05\x43urso\x12\x10\n\x08\x63urso_id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x15\n\rcupos_totales\x18\x03 \x01(\x05\x12\x14\n\x0c\x63upos_libres\x18\x04 \x01(\x05\"3\n\x14ListarCursosResponse\x12\x1b\n\x06\x63ursos\x18\x01 \x03(\x0b\x32\x0b.cupo.Curso\":\n\rOcuparRequest\x12\x10\n\x08\x63urso_id\x18\x01 \x01(\x05\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\".\n\x0eOcuparResponse\x12\x1c\n\x06\x65stado\x18\x01 \x01(\x0e\x32\x0c.cupo.Estado\";\n\x0eLiberarRequest\x12\x10\n\x08\x63urso_id\x18\x01 \x01(\x05\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\"/\n\x0fLiberarResponse\x12\x1c\n\x06\x65stado\x18\x01 \x01(\x0e\x32\x0c.cupo.Estado*m\n\x06\x45stado\x12\x16\n\x12\x45STADO_SIN_DEFINIR\x10\x00\x12\x10\n\x0c\x43UPO_OCUPADO\x10\x01\x12\r\n\tSIN_CUPOS\x10\x02\x12\x11\n\rCUPO_LIBERADO\x10\x03\x12\x17\n\x13\x43URSO_NO_ENCONTRADO\x10\x04\x32\xc5\x02\n\x05\x43upos\x12:\n\x0bobtenerCupo\x12\x14.cupo.ObtenerRequest\x1a\x15.cupo.ObtenerResponse\x12?\n\x0clistarCursos\x12\x13.cupo.ListarRequest\x1a\x1a.cupo.ListarCursosResponse\x12J\n\x17listarCursosDisponibles\x12\x13.cupo.ListarRequest\x1a\x1a.cupo.ListarCursosResponse\x12\x37\n\nocuparCupo\x12\x13.cupo.OcuparRequest\x1a\x14.cupo.OcuparResponse\x12:\n\x0bliberarCupo\x12\x14.cupo.LiberarRequest\x1a\x15.cupo.LiberarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cupos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESTADO']._serialized_start=474
  _globals['_ESTADO']._serialized_end=583
  _globals['_OBTENERREQUEST']._serialized_start=21
  _globals['_OBTENERREQUEST']._serialized_end=55
  _globals['_OBTENERRESPONSE']._serialized_start=57
  _globals['_OBTENERRESPONSE']._serialized_end=96
  _globals['_LISTARREQUEST']._serialized_start=98
  _globals['_LISTARREQUEST']._serialized_end=113
  _globals['_CURSO']._serialized_start=115
  _globals['_CURSO']._serialized_end=201
  _globals['_LISTARCURSOSRESPONSE']._serialized_start=203
  _globals['_LISTARCURSOSRESPONSE']._serialized_end=254
  _globals['_OCUPARREQUEST']._serialized_start=256
  _globals['_OCUPARREQUEST']._serialized_end=314
  _globals['_OCUPARRESPONSE']._serialized_start=316
  _globals['_OCUPARRESPONSE']._serialized_end=362
  _globals['_LIBERARREQUEST']._serialized_start=364
  _globals['_LIBERARREQUEST']._serialized_end=423
  _globals['_LIBERARRESPONSE']._serialized_start=425
  _globals['_LIBERARRESPONSE']._serialized_end=472
  _globals['_CUPOS']._serialized_start=586
  _globals['_CUPOS']._serialized_end=911
# @@protoc_insertion_point(module_scope)
