# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cupos_pb2 as cupos__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cupos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CuposStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.obtenerCupo = channel.unary_unary(
                '/cupo.Cupos/obtenerCupo',
                request_serializer=cupos__pb2.ObtenerRequest.SerializeToString,
                response_deserializer=cupos__pb2.ObtenerResponse.FromString,
                _registered_method=True)
        self.listarCursos = channel.unary_unary(
                '/cupo.Cupos/listarCursos',
                request_serializer=cupos__pb2.ListarRequest.SerializeToString,
                response_deserializer=cupos__pb2.ListarCursosResponse.FromString,
                _registered_method=True)
        self.listarCursosDisponibles = channel.unary_unary(
                '/cupo.Cupos/listarCursosDisponibles',
                request_serializer=cupos__pb2.ListarRequest.SerializeToString,
                response_deserializer=cupos__pb2.ListarCursosResponse.FromString,
                _registered_method=True)
        self.ocuparCupo = channel.unary_unary(
                '/cupo.Cupos/ocuparCupo',
                request_serializer=cupos__pb2.OcuparRequest.SerializeToString,
                response_deserializer=cupos__pb2.OcuparResponse.FromString,
                _registered_method=True)
        self.liberarCupo = channel.unary_unary(
                '/cupo.Cupos/liberarCupo',
                request_serializer=cupos__pb2.LiberarRequest.SerializeToString,
                response_deserializer=cupos__pb2.LiberarResponse.FromString,
                _registered_method=True)


class CuposServicer:
    """Missing associated documentation comment in .proto file."""

    def obtenerCupo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarCursos(self, request, context):
        """devuelve todos los cursos impartidos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarCursosDisponibles(self, request, context):
        """devuelve solo los cursos con cupos libres
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ocuparCupo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def liberarCupo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CuposServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'obtenerCupo': grpc.unary_unary_rpc_method_handler(
                    servicer.obtenerCupo,
                    request_deserializer=cupos__pb2.ObtenerRequest.FromString,
                    response_serializer=cupos__pb2.ObtenerResponse.SerializeToString,
            ),
            'listarCursos': grpc.unary_unary_rpc_method_handler(
                    servicer.listarCursos,
                    request_deserializer=cupos__pb2.ListarRequest.FromString,
                    response_serializer=cupos__pb2.ListarCursosResponse.SerializeToString,
            ),
            'listarCursosDisponibles': grpc.unary_unary_rpc_method_handler(
                    servicer.listarCursosDisponibles,
                    request_deserializer=cupos__pb2.ListarRequest.FromString,
                    response_serializer=cupos__pb2.ListarCursosResponse.SerializeToString,
            ),
            'ocuparCupo': grpc.unary_unary_rpc_method_handler(
                    servicer.ocuparCupo,
                    request_deserializer=cupos__pb2.OcuparRequest.FromString,
                    response_serializer=cupos__pb2.OcuparResponse.SerializeToString,
            ),
            'liberarCupo': grpc.unary_unary_rpc_method_handler(
                    servicer.liberarCupo,
                    request_deserializer=cupos__pb2.LiberarRequest.FromString,
                    response_serializer=cupos__pb2.LiberarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cupo.Cupos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cupo.Cupos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cupos:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def obtenerCupo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupo.Cupos/obtenerCupo',
            cupos__pb2.ObtenerRequest.SerializeToString,
            cupos__pb2.ObtenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listarCursos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupo.Cupos/listarCursos',
            cupos__pb2.ListarRequest.SerializeToString,
            cupos__pb2.ListarCursosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listarCursosDisponibles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupo.Cupos/listarCursosDisponibles',
            cupos__pb2.ListarRequest.SerializeToString,
            cupos__pb2.ListarCursosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ocuparCupo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupo.Cupos/ocuparCupo',
            cupos__pb2.OcuparRequest.SerializeToString,
            cupos__pb2.OcuparResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def liberarCupo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupo.Cupos/liberarCupo',
            cupos__pb2.LiberarRequest.SerializeToString,
            cupos__pb2.LiberarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
